version: '3.5'

services:
  api:
    image: saleschamp/php:7.1
    volumes:
     - .:/usr/src/app
    command: php -S 0.0.0.0:8080 -t public index.php
    working_dir: /usr/src/app
    stop_signal: SIGINT
    ports:
      - 8080

